In [0]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
#from sklearn.model_selection import train_test_split
from tensorflow.keras.datasets import mnist
from keras.utils import np_utils

In [4]:
(x_train,y_train), (x_test,y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [5]:
x_train.shape

(60000, 28, 28)

In [8]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
y_train.shape

(60000,)

In [7]:
x_test.shape

(10000, 28, 28)

In [0]:
x_train = x_train.reshape(x_train.shape[0],x_train.shape[1]*x_train.shape[2])

In [10]:
x_train.shape

(60000, 784)

In [0]:
x_test = x_test.reshape(x_test.shape[0],28*28)

In [12]:
x_test.shape

(10000, 784)

In [13]:
y_train[0]

5

In [0]:
y_train = np_utils.to_categorical(y_train,10)
y_test = np_utils.to_categorical(y_test,10)

In [15]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [16]:
x_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [0]:
x_train = x_train/255
x_test = x_test/255

In [0]:
model = Sequential()

In [0]:
model.add(Dense(32, input_shape=(784,)))
model.add(Dense(64,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                25120     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 36,842
Trainable params: 36,842
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
model.fit(x_train,y_train,epochs=10, batch=200)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2886 - accuracy: 0.9145
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1420 - accuracy: 0.9569
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1097 - accuracy: 0.9658
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0896 - accuracy: 0.9722
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0776 - accuracy: 0.9752
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0658 - accuracy: 0.9785
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0583 - accuracy: 0.9813
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0521 - accuracy: 0.9837
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0454 - accuracy: 0.9854
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.043

In [23]:
score = model.evaluate(x_test,y_test) #loss,acc = all same

313/313 [==============================] - 1s 3ms/step - loss: 0.1106 - accuracy: 0.9716


In [24]:
score[1] # accuracy

0.9715999960899353

In [25]:
score[0] #loss

0.11062300205230713

In [26]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch=200)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0383 - accuracy: 0.9874 - val_loss: 0.1237 - val_accuracy: 0.9696
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0380 - accuracy: 0.9878 - val_loss: 0.1057 - val_accuracy: 0.9734
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0345 - accuracy: 0.9886 - val_loss: 0.1002 - val_accuracy: 0.9749
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0304 - accuracy: 0.9898 - val_loss: 0.1038 - val_accuracy: 0.9739
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0276 - accuracy: 0.9909 - val_loss: 0.1147 - val_accuracy: 0.9746
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0275 - accuracy: 0.9910 - val_loss: 0.1053 - val_accuracy: 0.9755
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0265 - accuracy: 0.9911 - val_loss: 0.1056 - val_accuracy: